repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        exclude: .*/migrations/.*

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: .*/migrations/.*
        
  - repo: local
    hooks:
      - id: pylint-django
        name: pylint-django
        entry: pylint
        language: system
        types: [python]
        files: ^django_task_manager/
        args: [--rcfile=django_task_manager/.pylintrc]

      - id: pylint-fastapi
        name: pylint-fastapi
        entry: pylint
        language: system
        types: [python]
        files: ^fastapi_task_manager/
        args: [--rcfile=fastapi_task_manager/.pylintrc]