openapi: 3.0.3
info:
  title: Task API Project
  version: 1.0.0
  description: A simple Task Manager
paths:
  /api/v1/task/{uuid}/:
    get:
      operationId: api_v1_task_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1_task_create
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_v1_task_update
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_v1_task_destroy
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/task/create/:
    get:
      operationId: api_v1_task_create_retrieve
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1_task_create_create
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_v1_task_create_update
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_v1_task_create_destroy
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/task/delete/{uuid}/:
    get:
      operationId: api_v1_task_delete_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1_task_delete_create
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_v1_task_delete_update
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_v1_task_delete_destroy
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/task/update/{uuid}/:
    get:
      operationId: api_v1_task_update_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1_task_update_create
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_v1_task_update_update
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_v1_task_update_destroy
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/tasklist/:
    get:
      operationId: api_v1_tasklist_retrieve
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1_tasklist_create
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_v1_tasklist_update
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_v1_tasklist_destroy
      tags:
      - api
      security:
      - basicAuth: []
      responses:
        '204':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
